config/routes.rb
Rails.application.routes.draw do

  get 'stampings/index'
  post 'stampings/go_to_work'

  get 'calendars/index'

  get 'kintai_header/edit/:id', to: 'kintai_header#edit'
  patch 'kintai_header/update/:id', to: 'kintai_header#update'

  get 'attendance_information/index'
  get 'attendance_information/create_pre_month'
  get 'attendance_information/create_next_month'

  resources :katagakis

  resources :summary_attendances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
      get 'calculate'
      get 'print'
      post 'search'
    end
  end

  resources :housing_allowances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  get 'resumes/index'
  get 'resumes/print'

  resources :commutes do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :reasons

  resources :attendance_others

  resources :licenses
  resources :projects

  resources :transportation_expresses do
    collection do
      post 'transportation_confirm'
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :vacation_requests do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :business_reports, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :business_reports

  resource :qualification_allowances, only:[] do
    get :print
  end
  resources :qualification_allowances

  match '/index_freeze', to:'papers#index_freeze', via: :get

  resources :kinmu_patterns, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :kinmu_patterns
  resources :sections
  resources :attendances, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  match '/init_attendances', to:'attendances#init_attendances', via: :get
  match '/calculate_attendance', to:'attendances#calculate', via: :get
  match '/input_attendance_time', to:'attendances#input_attendance_time', via: :get

  match '/freeze_up', to:'papers#freeze_up', via: :get
  match '/cancel_freeze', to:'papers#cancel_freeze', via: :get

  resource :attendances, only: [] do
    get :print
  end

  match '/home', to:'static_pages#home', via: :get
  match '/help', to:'static_pages#help', via: :get
  match '/about', to:'static_pages#about', via: :get

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

end

app/models/attendance_other.rb
class AttendanceOther < ActiveRecord::Base
  belongs_to :user

  attr_accessor :is_negative_other_over_time
  attr_accessor :is_negative_other_holiday_time
  attr_accessor :is_negative_other_midnight_time
  attr_accessor :is_negative_other_break_time
  attr_accessor :is_negative_other_kouzyo_time
  attr_accessor :is_negative_other_work_time

  validates :summary, length: { maximum: 7 }
  validates :remarks, length: { maximum: 10 }

  validate :check_negative, on: :update

  def check_negative

    if self.is_negative_other_over_time
      errors[:base] << "超過時間にマイナスの値を入力することはできません."
    end
    if self.is_negative_other_holiday_time
      errors[:base] << "休日時間にマイナスの値を入力することはできません。"
    end
    if self.is_negative_other_midnight_time
      errors[:base] << "深夜時間にマイナスの値を入力することはできません。 "
    end
    if self.is_negative_other_break_time
      errors[:base] << "休憩時間にマイナスの値を入力することはできません。"
    end
    if self.is_negative_other_kouzyo_time
      errors[:base] << "控除時間にマイナスの値を入力することはできません。"
    end
    if self.is_negative_other_work_time
      errors[:base] << "実働時間にマイナスの値を入力することはできません。"
    end

  end

end

app/controllers/attendance_others_controller.rb
# -*- coding: utf-8 -*-
class AttendanceOthersController < ApplicationController
  before_action :set_attendance_other, only: [:show, :edit, :update, :destroy]

  # GET /attendance_others
  # GET /attendance_others.json
  def index
    @attendance_others = current_user.attendan_others
  end

  # GET /attendance_others/1
  # GET /attendance_others/1.json
  def show
  end

  # GET /attendance_others/new
  def new
    @attendance_other = AttendanceOther.new
  end

  # GET /attendance_others/1/edit
  def edit
  end

  # POST /attendance_others
  # POST /attendance_others.json
  def create
    @attendance_other = AttendanceOther.new(attendance_other_params)

    if @attendance_other.save
      redirect_to @attendance_other, notice: '作成しました。'
    else
      render :new
    end
  end

  # PATCH/PUT /attendance_others/1
  # PATCH/PUT /attendance_others/1.json
  def update

    # 入力チェック
    @attendance_other.is_negative_other_over_time = false
    @attendance_other.is_negative_other_holiday_time = false
    @attendance_other.is_negative_other_midnight_time = false
    @attendance_other.is_negative_other_break_time = false
    @attendance_other.is_negative_other_kouzyo_time = false
    @attendance_other.is_negative_other_work_time = false

    if params[:attendance_other]['over_time'].to_d < 0
      @attendance_other.is_negative_other_over_time = true
    end
    if params[:attendance_other]['holiday_time'].to_d < 0
      @attendance_other.is_negative_other_holiday_time = true
    end
    if params[:attendance_other]['midnight_time'].to_d < 0
      @attendance_other.is_negative_other_midnight_time = true
    end
    if params[:attendance_other]['break_time'].to_d < 0
      @attendance_other.is_negative_other_break_time = true
    end
    if params[:attendance_other]['kouzyo_time'].to_d < 0
      @attendance_other.is_negative_other_kouzyo_time = true
    end
    if params[:attendance_other]['work_time'].to_d < 0
      @attendance_other.is_negative_other_work_time = true
    end


    if @attendance_other.update(attendance_other_params)
      redirect_to attendances_path, notice: '更新しました。'
    else
      render :edit
    end
  end

  # DELETE /attendance_others/1
  # DELETE /attendance_others/1.json
  def destroy
    @attendance_other.destroy
    redirect_to attendance_others_url, notice: '削除しました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance_other
      @attendance_other = AttendanceOther.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_other_params
      params.require(:attendance_other).permit(:summary, :start_time, :end_time, :over_time, :holiday_time, :midnight_time,:break_time, :kouzyo_time, :work_time, :remarks, :user_id, :year, :month)
    end
end

app/helpers/attendance_others_helper.rb
module AttendanceOthersHelper
end

app/views/attendance_others/_form.html.slim
.row
  .large-12.columns
    = form_for @attendance_other do |f|
      - if @attendance_other.errors.any?
      = render 'shared/error_messages', object: f.object

      = f.hidden_field :year
      = f.hidden_field :month

      .row
        .large-1.columns.show-for-large-up
          label.left.inline 名称
        .large-1.large-pull-10.columns
          = f.text_field :summary, :maxlength => 7
      .row
        .large-1.columns.show-for-large-up
          label.left.inline 出勤
        .large-3.large-pull-8.columns
          = f.time_select :start_time
      .row
        .large-1.columns.show-for-large-up
          label.left.inline 退勤
        .large-3.large-pull-8.columns
          = f.time_select :end_time
      .row
        .large-1.small-4.columns
          label.left.inline 超過時間
        .large-1.large-pull-10.small-8.columns
          = f.number_field :over_time, :value => number_with_precision(f.object.over_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.small-4.columns
          label.left.inline 休日時間
        .large-1.large-pull-10.small-8.columns
          = f.number_field :holiday_time, :value => number_with_precision(f.object.holiday_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.small-4.columns
          label.left.inline 深夜時間
        .large-1.large-pull-10.small-8.columns
          = f.number_field :midnight_time, :value => number_with_precision(f.object.midnight_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.small-4.columns
          label.left.inline 休憩時間
        .large-1.large-pull-10.small-8.columns
          = f.number_field :break_time, :value => number_with_precision(f.object.break_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.small-4.columns
          label.left.inline 控除時間
        .large-1.large-pull-10.small-8.columns
          = f.number_field :kouzyo_time, :value => number_with_precision(f.object.kouzyo_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.columns.show-for-large-up
          label.left.inline 実働時間
        .large-1.large-pull-10.columns
          = f.number_field :work_time, :value => number_with_precision(f.object.work_time,:precision => 2), :step => 0.25, :min => 0, :max => 99.75
      .row
        .large-1.small-4.columns
          label.left.inline 備考
        .large-4.large-pull-7.small-8.columns
          = f.text_area :remarks, :maxlength => 10
      .row
        .large-6.large-centered.columns
          = f.submit "登録", class: "button radius", id: "submit"
          = link_to '戻る', attendances_path, class: "button radius"

app/views/attendance_others/edit.html.slim
article.attendance_others.edit
  .row
    .large-12.columns
      h3 勤務状況情報の修正

      == render 'form'

app/views/attendance_others/index.html.slim
article.attendance_other_index
  .row
    table
      thead
        tr
          th Summary
          th Over time
          th
          th
          th

      tbody
        - @attendance_others.each do |attendance_other|
          tr
            td = attendance_other.summary
            td = attendance_other.over_time
            td = link_to 'Show', attendance_other
            td = link_to 'Edit', edit_attendance_other_path(attendance_other)
            td = link_to 'Destroy', attendance_other, data: {:confirm => 'Are you sure?'}, :method => :delete

    br

    = link_to 'New Attendance other', new_attendance_other_path

app/views/attendance_others/new.html.slim
h1 New attendance_other

== render 'form'

= link_to 'Back', attendance_others_path

app/views/attendance_others/show.html.slim
p#notice = notice

p
  strong Summary:
  = @attendance_other.summary
p
  strong Over time:
  = @attendance_other.over_time

= link_to 'Edit', edit_attendance_other_path(@attendance_other)
'|
= link_to 'Back', attendance_others_path