config/routes.rb
Rails.application.routes.draw do

  get 'stampings/index'
  post 'stampings/go_to_work'

  get 'calendars/index'

  get 'kintai_header/edit/:id', to: 'kintai_header#edit'
  patch 'kintai_header/update/:id', to: 'kintai_header#update'

  get 'attendance_information/index'
  get 'attendance_information/create_pre_month'
  get 'attendance_information/create_next_month'

  resources :katagakis

  resources :summary_attendances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
      get 'calculate'
      get 'print'
      post 'search'
    end
  end

  resources :housing_allowances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  get 'resumes/index'
  get 'resumes/print'

  resources :commutes do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :reasons

  resources :attendance_others

  resources :licenses
  resources :projects

  resources :transportation_expresses do
    collection do
      post 'transportation_confirm'
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :vacation_requests do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :business_reports, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :business_reports

  resource :qualification_allowances, only:[] do
    get :print
  end
  resources :qualification_allowances

  match '/index_freeze', to:'papers#index_freeze', via: :get

  resources :kinmu_patterns, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :kinmu_patterns
  resources :sections
  resources :attendances, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  match '/init_attendances', to:'attendances#init_attendances', via: :get
  match '/calculate_attendance', to:'attendances#calculate', via: :get
  match '/input_attendance_time', to:'attendances#input_attendance_time', via: :get

  match '/freeze_up', to:'papers#freeze_up', via: :get
  match '/cancel_freeze', to:'papers#cancel_freeze', via: :get

  resource :attendances, only: [] do
    get :print
  end

  match '/home', to:'static_pages#home', via: :get
  match '/help', to:'static_pages#help', via: :get
  match '/about', to:'static_pages#about', via: :get

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

end

app/models/qualification_allowance.rb
class QualificationAllowance < ActiveRecord::Base
	belongs_to :user

  ITEM = 
    [["A1 : ITストラテジスト","ITストラテジスト"],
     ["A2 : システム監査技術者","システム監査技術者"],
     ["A3 : システムアーキテクト","システムアーキテクト"],
     ["A4 : 応用情報技術者","応用情報技術者"],
     ["A5 : プロジェクトマネージャー","プロジェクトマネージャー"],
     ["A6 : ネットワークスペシャリスト","ネットワークスペシャリスト"],
     ["A7 : データベーススペシャリスト","データベーススペシャリスト"],
     ["A8 : エンベンデットシステムスペシャリスト","エンベンデットシステムスペシャリスト"],
     ["A9 : 情報セキュリティースペシャリスト","情報セキュリティースペシャリスト"],
     ["A10 : ITサービスマネーシャー","ITサービスマネーシャー"],
     ["A11 : 基本情報技術者","基本情報技術者"],
     ["A12 : ITパスポート","ITパスポート"]]

  NUMBER = 
    [["A1 : ITストラテジスト","A1"],
     ["A2 : システム監査技術者","A2"],
     ["A3 : システムアーキテクト","A3"],
     ["A4 : 応用情報技術者","A4"],
     ["A5 : プロジェクトマネージャー","A5"],
     ["A6 : ネットワークスペシャリスト","A6"],
     ["A7 : データベーススペシャリスト","A7"],
     ["A8 : エンベンデットシステムスペシャリスト","A8"],
     ["A9 : 情報セキュリティースペシャリスト","A9"],
     ["A10 : ITサービスマネーシャー","A10"],
     ["A11 : 基本情報技術者","A11"],
     ["A12 : ITパスポート","A12"]]

  MONEY = 
    [["A1~A3 : 30000 円","30000"],
     ["A4~A10 : 20000 円","20000"],
     ["A11 : 10000 円","10000"],
     ["A12 : 3000 円","3000"]]

  ALPHABET = 
    [["ST","ST"],
     ["AU","AU"],
     ["SA","SA"],
     ["AP","AP"],
     ["PM","PM"],
     ["NW","NW"],
     ["DB","DB"],
     ["ES","ES"],
     ["SC","SC"],
     ["SM","SM"],
     ["FE","FE"],
     ["IP","IP"]]
end

app/controllers/qualification_allowances_controller.rb
class QualificationAllowancesController < ApplicationController
  before_action :set_qualification_allowance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @project = get_project
    @qualification_allowances = current_user.qualification_allowances.all
  end

  def show
    @qualification_allowances = current_user.qualification_allowances.find(params[:id])
  end

  def new
    @qualification_allowance = current_user.qualification_allowances.build
  end

  def edit
  end

  def create
    @qualification_allowance = current_user.qualification_allowances.build(qualification_allowance_params)

    respond_to do |format|
      if @qualification_allowance.save
        format.html { redirect_to qualification_allowances_url, notice: '資格手当申請書を登録しました' }
        format.json { render :show, status: :created, location: @qualification_allowance }
      else
        format.html { render :new }
        format.json { render json: @qualification_allowance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @qualification_allowance.update(qualification_allowance_params)
        format.html { redirect_to qualification_allowances_url, notice: '資格手当申請書を更新しました' }
        format.json { render :show, status: :ok, location: @qualification_allowance }
      else
        format.html { render :edit }
        format.json { render json: @qualification_allowance.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @qualification_allowance.destroy
    respond_to do |format|
      format.html { redirect_to qualification_allowances_url, notice: '資格手当申請書を削除しました' }
      format.json { head :no_content }
    end
  end

  def print

    year = Date.today.year
    month = Date.today.month
    day = Date.today.day
    
    @nendo = Date.today.year
    @gatudo = Date.today.month

    if Date.today.month == 12 and Date.today.day > 15
      @nendo = Date.today.years_since(1).year
    end
    @qualification_allowances = QualificationAllowance.all
    @qualification_allowances = current_user.qualification_allowances.all
    @project = current_user.projects.find_by(active: true)
    @date = @qualification_allowances.maximum(:updated_at ,:include)

    @qualification_allowance = current_user.qualification_allowances.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
    
    respond_to do |format|

      format.html { redirect_to print_qualification_allowances_path(format: :pdf, debug: 1)}
      format.pdf do
        render pdf: '資格手当申請書',
               encoding: 'UTF-8',
               layout: 'pdf.html',
               show_as_html: params[:debug].present?
      end
    end
  end

  private
    def set_qualification_allowance
      @qualification_allowance = QualificationAllowance.find(params[:id])
    end

    def qualification_allowance_params
      params.require(:qualification_allowance).permit(
        :user_id, :number, :item, :money, :get_date, :registration_no_alphabet,
        :registration_no_year, :registration_no_month, :registration_no_individual)
    end
end

app/helpers/qualification_allowances_helper.rb
module QualificationAllowancesHelper
end

app/views/qualification_allowances/_form.html.slim
.row
  .large-5.columns
    = form_for @qualification_allowance, :html => {:name => 'itemForm', :onChange => 'functionName()'} do |f|
      - if @qualification_allowance.errors.any?
        #error_explanation
          h2 = "#{pluralize(@qualification_allowance.errors.count, "error")} prohibited this qualification_allowance from being saved:"
          ul
            - @qualification_allowance.errors.full_messages.each do |message|
              li = message

      .small-5.columns style="margin-left: -15px;"
        label 資格取得年月日
        = f.date_field :get_date
        / = f.date_select :get_date

      table
        tr
          td 登&nbsp;録&nbsp;番&nbsp;号&nbsp;&nbsp;&nbsp;&nbsp;
        tr.left style="background-color: #fff; width: 525px; height: 65px;"
          td style="padding-top: 0px;" 第
          td width="70" = f.select :registration_no_alphabet, QualificationAllowance::ALPHABET
          td style="padding-top: 0px;" ―
          td width="80" = f.text_field :registration_no_year
          td style="padding-top: 0px;" ―
          td width="60" = f.text_field :registration_no_month
          td style="padding-top: 0px;" ―
          td width="90" = f.text_field :registration_no_individual
          td style="padding-top: 0px;" 号

      .field
        label No.
        = f.select :number, QualificationAllowance::NUMBER, {:include_blank => '▼ 選択してください'}

      .field 
        label 資格取得項目
        = f.select :item, QualificationAllowance::ITEM

      .field 
        label 支給金額
        = f.select :money, QualificationAllowance::MONEY

      .row
        .large-7.large-centered.columns
          = f.submit '登録', class: "button tiny radius"
          = link_to '戻る', qualification_allowances_path, class: "button tiny radius gray"

app/views/qualification_allowances/edit.html.slim
h3 style="padding-left: 15px;" 資格手当申請書 編集

== render 'form'

/ = link_to '照会', @qualification_allowance
/ '|
/ = link_to '前に戻る', qualification_allowances_path, class: "button tiny radius"

app/views/qualification_allowances/index.html.slim
article.qualification_allowance_index
  h3 style="padding-left: 10px;" 資格手当申請書
  #qualification_allowance_header.clearfix
    table#qualification_allowance_project
      tbody
        tr style="height: 20px;"
          td プロジェクト名:
          td = truncate(@project.summary, length:20) if ! @project.nil?
        tr style="height: 20px;"
          td 所属:
          td = current_user.section.name if ! current_user.section.nil?
        tr style="height: 20px;"
          td 氏名:
          td #{current_user.family_name} #{current_user.first_name}

|&nbsp;&nbsp;&nbsp;
= link_to print_qualification_allowances_path, class: "button tiny radius" do
  i.fi-print
  | 印刷用画面
|&nbsp;&nbsp;&nbsp;
= link_to '新規作成', new_qualification_allowance_path, class: "button tiny radius"
- @qualification_allowances.each do |qualification_allowance|
  tbody
    tr
      td = link_to '編 集', edit_qualification_allowance_path(qualification_allowance), class: "button tiny radius"
      td = link_to '削 除', qualification_allowance, data: {:confirm => '削除してもよろしいですか?'}, :method => :delete, class: "button tiny radius"

  table style="margin-left: 15px;"
    thead
      tr
        th 資格取得年月日
        th No.
        th 資格取得項目
        th 支給金額
    tbody
      tr
        td = qualification_allowance.get_date
        td = qualification_allowance.number
        td = qualification_allowance.item
        td #{qualification_allowance.money} 円

  table#qualification_allowance style="margin-top: -22px; margin-left: 15px;"
    tr
      td 登&nbsp;録&nbsp;番&nbsp;号&nbsp;&nbsp;&nbsp;&nbsp;第
      td #{qualification_allowance.registration_no_alphabet}
      td ―
      td #{qualification_allowance.registration_no_year}
      td ―
      td #{qualification_allowance.registration_no_month}
      td ―
      td #{qualification_allowance.registration_no_individual}
      td 号

app/views/qualification_allowances/new.html.slim
h1 資格手当申請書 作成

== render 'form'

/ = link_to '前に戻る', qualification_allowances_path, class: "button tiny radius"

app/views/qualification_allowances/print.pdf.slim
article.qualification_allowance_print
	#qualification_allowance_header.clearfix
		#qualification_allowance_for.left
			tbody
				tr
					td 総務人事部　殿
		div.left
			h3#qualification_allowance_title.left 資格手当申請書

		table#qualification_allowance_inkan.left border="1"
			tbody
				tr
					td.in.text-center 人&nbsp;事
					td.in.text-center 所属長
					td.in.text-center 本&nbsp;人
				tr height="65"
					td
					td
					td
    div.left
      h6#qualification_allowance_request 
       | 申 請 　平成#{@nendo-1988}#{ @date.strftime("年%_m月%_d日")}

	table#qualification_allowance_user border="1"
		tr width="640" height="45"
			td.us width="145" 所&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;属
			td.us width="250" = current_user.section.name if ! current_user.section.nil?
			td width="290" 
		tr height="45"
			td.us 氏&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名
			td.us #{current_user.family_name} #{current_user.first_name}
			td.us 社員NO : #{current_user.employee_no}

- @qualification_allowances.each do |qualification_allowance|
	table#qualification_allowance_year border="1"
		tr
			td.ye1 資格取得年月日
			td.ye #{qualification_allowance.get_date}
		tr
			td.ye2 取得No.【 #{qualification_allowance.number} 】
			td.ye2 登&nbsp;録&nbsp;番&nbsp;号&nbsp;&nbsp;&nbsp&nbsp&nbsp;第 #{qualification_allowance.registration_no_alphabet} ― #{qualification_allowance.registration_no_year} ― #{qualification_allowance.registration_no_month} ― #{qualification_allowance.registration_no_individual} 号 （コピー添付）

	table#qualification_allowance_item border="1"
		tr
			td.it1 No.
			td.it 資&nbsp;&nbsp;&nbsp;格&nbsp;&nbsp;&nbsp;取&nbsp;&nbsp;&nbsp;得&nbsp;&nbsp;&nbsp;項&nbsp;&nbsp;&nbsp;目
			td.it2 支給金額
		tr
			td.no A1
			td ITストラテジスト
			td.no 30,000
		tr
			td.no A2
			td システム監査技術者
			td.no 30,000
		tr
			td.no A3
			td システムアーキテクト
			td.no 30,000
		tr
			td.no A4
			td 応用情報技術者
			td.no 20,000
		tr
			td.no A5
			td プロジェクトマネージャー
			td.no 20,000
		tr
			td.no A6
			td ネットワークスペシャリスト
			td.no 20,000
		tr
			td.no A7
			td データーベーススペシャリスト
			td.no 20,000
		tr
			td.no A8
			td エンベンデットシステムスペシャリスト
			td.no 20,000
		tr
			td.no A9
			td 情報セキュリティースペシャリスト
			td.no 20,000
		tr
			td.no A10
			td ITサービスマネージャー
			td.no 20,000
		tr
			td.no A11
			td 基本情報技術者
			td.no 10,000
		tr
			td.no A12
			td ITパスポート
			td.no 3,000
			
	table#qualification_allowance_money border="1"
		tr
			td.cal （人事記入欄）&nbsp;&nbsp;&nbsp;&nbsp;支&nbsp;&nbsp;給&nbsp;&nbsp;金&nbsp;&nbsp;額&nbsp;
			td.mon #{qualification_allowance.money} 円
    div.left
      h6#qualification_allowance_fotter 
       | 株式会社　システム・スクゥェアー

app/views/qualification_allowances/show.html.slim
p#notice = notice

/ p
/   strong User:
/   = @qualification_allowance.user_id
p
	strong 資格取得年月日 : 
	= @qualification_allowance.get_date
p
  strong No. : 
  = @qualification_allowance.number
p
  strong 資格取得項目 : 
  = @qualification_allowance.item
p
  strong 支給金額 : 
  = @qualification_allowance.money

= link_to '編集', edit_qualification_allowance_path(@qualification_allowance)
'|
= link_to '前に戻る', qualification_allowances_path