config/routes.rb
Rails.application.routes.draw do

  get 'stampings/index'
  post 'stampings/go_to_work'

  get 'calendars/index'

  get 'kintai_header/edit/:id', to: 'kintai_header#edit'
  patch 'kintai_header/update/:id', to: 'kintai_header#update'

  get 'attendance_information/index'
  get 'attendance_information/create_pre_month'
  get 'attendance_information/create_next_month'

  resources :katagakis

  resources :summary_attendances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
      get 'calculate'
      get 'print'
      post 'search'
    end
  end

  resources :housing_allowances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  get 'resumes/index'
  get 'resumes/print'

  resources :commutes do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :reasons

  resources :attendance_others

  resources :licenses
  resources :projects

  resources :transportation_expresses do
    collection do
      post 'transportation_confirm'
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :vacation_requests do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :business_reports, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :business_reports

  resource :qualification_allowances, only:[] do
    get :print
  end
  resources :qualification_allowances

  match '/index_freeze', to:'papers#index_freeze', via: :get

  resources :kinmu_patterns, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :kinmu_patterns
  resources :sections
  resources :attendances, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  match '/init_attendances', to:'attendances#init_attendances', via: :get
  match '/calculate_attendance', to:'attendances#calculate', via: :get
  match '/input_attendance_time', to:'attendances#input_attendance_time', via: :get

  match '/freeze_up', to:'papers#freeze_up', via: :get
  match '/cancel_freeze', to:'papers#cancel_freeze', via: :get

  resource :attendances, only: [] do
    get :print
  end

  match '/home', to:'static_pages#home', via: :get
  match '/help', to:'static_pages#help', via: :get
  match '/about', to:'static_pages#about', via: :get

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .row
    .large-12.columns
      #error_explanation
        .alert-box.error.radius data-alert=""
          | #{object.errors.count}件のエラーがあります。
        .row
          .large-12.columns
            ul.pricing-table
              - object.errors.full_messages.each do |msg|
                li.bullet-item.left
                  | * #{msg}

app/views/shared/_paper_proc.html.slim
.row
  .larte-12.columns
    = form_tag target, method: "get" do
      .row
        .large-3.columns
            .attendances_hearder
              = link_to '◀', pre_path, class:"button tiny radius"
              / = collection_select :paper, :years, years, :id, :value, {selected: session[:years]}
              = select_tag 'paper[years]', options_for_select(years, selected: session[:years])
              |&nbsp;&nbsp;
              = link_to '▶', next_path, class:"button tiny radius"

        - if can? :manage, current_user
          .large-2.columns
              .attendances_hearder
                tbody
                  tr
                    td 対象ユーザー
                    td = collection_select :user, :id, users, :id, :value, {selected: session[:target_user]}
          .large-7.columns
        - else
          .large-9.columns



.row
  .large-12.columns
    #paper_header
      = link_to raw("<i class='fi-print'></i>ヘッダー情報の修正"), {controller: :kintai_header, action: "edit", id: kintai_header.id}, {class: "button tiny radius"}
      table#paper_project
        tbody
          tr
            td 氏名:
            td = kintai_header.user_name
          tr
            td 所属:
            td = kintai_header.section_name unless kintai_header.section_name.blank?
          tr
            td プロジェクト名:
            td = truncate(kintai_header.project_name, length:20) unless kintai_header.project_name.blank?
          tr
            td ステータス:
            td = status

hr
.row
  .large-12.columns
    / 新規作成
    - if target!="attendances" and target!="housing_allowances" and target!="summary_attendances" and target!="business_reports"
      = link_to raw("<i class='fi-plus'></i>新規追加"),{controller: target, action: "new"},{class: "button tiny radius"}
    / 編集ボタン 住宅手当申請書は新規追加の必要が無い為
    - if target=="housing_allowances"
      = link_to raw("<i class='fi-pencil'></i>編集"),{controller: target, id: contents , action: "edit" },{class: "button tiny radius"}
    / 印刷処理
    = link_to raw("<i class='fi-print'></i>印刷用画面"), {controller: target, action: "print"}, {class: "button tiny radius"}

    / データ初期化
    - if target == "attendances"
      - unless@freezed
        = link_to raw("<i class='fi-refresh'></i>データ初期化"), {controller: target, action: "init_attendances"}, {data: {:confirm => '今月度の勤怠データを初期化します。宜しいですか？'}, class: "button tiny radius"}

    / 本人確認
    - if status == "本人未確認"
      = link_to raw("<i class='fi-refresh'></i>本人確認"), {controller: target, action: "check"}, {data: {:confirm => '今月度の勤怠情報を確定します。宜しいですか？'}, class: "button tiny radius success"}
    - else
      = link_to raw("<i class='fi-refresh'></i>本人確認取消し"), {controller: target, action: "cancel_check"}, {data: {:confirm => '今月度の勤怠情報を確定します。宜しいですか？'}, class: "button tiny radius alert"}

    / 上長承認(マネージャークラス以上の場合のみ表示)
    - if can? :manage, current_user
      - if status == "上長承認済み"
        = link_to raw("<i class='fi-refresh'></i>上長承認取消し"), {controller: target, action: "cancel_approval"}, {data: {:confirm => '今月度の勤怠情報を確定します。宜しいですか？'}, class: "button tiny radius alert"}
      - else
        = link_to raw("<i class='fi-refresh'></i>上長承認"), {controller: target, action: "approve"}, {data: {:confirm => '今月度の勤怠情報を確定します。宜しいですか？'}, class: "button tiny radius success"}

app/views/shared/_search.html.slim
.row
  .larte-12.columns
    .information_hearder
      = form_tag search_summary_attendances_path, :method => :post do
        .row
          .large-1.small-4.columns
            label.left.inline 年月
          .large-3.large-pull-8.small-8.columns
            = select_tag 'search[years]', options_for_select(years, selected: session[:years])
        .row
          .large-1.small-4.columns
            label.left.inline 課
          .large-3.large-pull-8.small-8.columns
            = collection_select :search, :sections, sections, :id, :value, {selected: session[:sections], include_blank: true}
        
        .row
          .large-6.large-centered.text-center.columns
            = submit_tag "検  索", class: "button small radius", id: "go_to_work"

app/views/shared/_years.html.slim
.row
  .larte-12.columns
    .row
      .large-3.columns
        .information_hearder
          = form_tag target, :method => :get do
            = link_to '◀', pre_path, class:"button tiny radius"
            = select_tag 'paper[years]', options_for_select(years, selected: session[:years])
            |&nbsp;&nbsp;
            = link_to '▶', next_path, class:"button tiny radius"