config/routes.rb
Rails.application.routes.draw do

  get 'stampings/index'
  post 'stampings/go_to_work'

  get 'calendars/index'

  get 'kintai_header/edit/:id', to: 'kintai_header#edit'
  patch 'kintai_header/update/:id', to: 'kintai_header#update'

  get 'attendance_information/index'
  get 'attendance_information/create_pre_month'
  get 'attendance_information/create_next_month'

  resources :katagakis

  resources :summary_attendances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
      get 'calculate'
      get 'print'
      post 'search'
    end
  end

  resources :housing_allowances do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  get 'resumes/index'
  get 'resumes/print'

  resources :commutes do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :reasons

  resources :attendance_others

  resources :licenses
  resources :projects

  resources :transportation_expresses do
    collection do
      post 'transportation_confirm'
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :vacation_requests do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :business_reports, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  resources :business_reports

  resource :qualification_allowances, only:[] do
    get :print
  end
  resources :qualification_allowances

  match '/index_freeze', to:'papers#index_freeze', via: :get

  resources :kinmu_patterns, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'create_pre_month'
      get 'create_next_month'
    end
  end

  resources :kinmu_patterns
  resources :sections
  resources :attendances, only:[:index, :new, :create, :edit, :update] do
    collection do
      get 'print'
      get 'check'
      get 'cancel_check'
      get 'approve'
      get 'cancel_approval'
      get 'create_pre_month'
      get 'create_next_month'
    end
  end
  match '/init_attendances', to:'attendances#init_attendances', via: :get
  match '/calculate_attendance', to:'attendances#calculate', via: :get
  match '/input_attendance_time', to:'attendances#input_attendance_time', via: :get

  match '/freeze_up', to:'papers#freeze_up', via: :get
  match '/cancel_freeze', to:'papers#cancel_freeze', via: :get

  resource :attendances, only: [] do
    get :print
  end

  match '/home', to:'static_pages#home', via: :get
  match '/help', to:'static_pages#help', via: :get
  match '/about', to:'static_pages#about', via: :get

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

end

app/models/commute.rb
class Commute < ActiveRecord::Base
	belongs_to :user 
end

app/controllers/commutes_controller.rb
class CommutesController < PapersController
  before_action :set_commute, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /commutes
  # GET /commutes.json
  def index

    init

    session[:years] = "#{@nendo}#{@gatudo}"

    create_commutes
    create_reasons

    unless view_context.target_user.kintai_headers.exists?(year: @nendo.to_s,month: @gatudo.to_s)
      create_kintai_header
    end
    
    @years = create_years_collection view_context.target_user.commutes # 対象年月リスト 要修正
    @users = create_users_collection

    @sum=0
    if !@commutes.blank?
      @freezed = @commutes.first.freezed
    else
      @freezed = @commutes.first.freezed
    end
     @date=@commutes.maximum(:updated_at ,:include)  #更新日時が一番新しいものを取得
    if @date==nil                                                 #更新日時が空なら今日の日付を使用
      @date=Date.today
    end

    # =============
    @status = "本人未確認"
    unless @commutes.first.nil?
      if @commutes.first.freezed
        @status = "凍結中"
      elsif @commutes.first.boss_approved
        @status = "上長承認済み"
      elsif @commutes.first.self_approved
        @status = "本人確認済み"
      end
    end
    # =============


    # @commutes = Commute.all
    # @commute=current_user.commutes.all
    @reasons=Reason.all
    @reasons=current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s).first
    # @sum=0

    # @project = current_user.projects.find_by(active: true)

    # @date=@commute.maximum(:updated_at ,:include)  #更新日時が一番新しいものを取得
    # if @date==nil                                                 #更新日時が空なら今日の日付を使用
    #   @date=Date.today
    # end

  end

  # GET /commutes/1
  # GET /commutes/1.json
  def show
  end

  # GET /commutes/new
  def new
    init
    @commute = current_user.commutes.build
    # @commute = Commute.new
  end

  def print_proc
    years = session[:years]
     @sum = session[:sum]
    if years.nil?
      commute_years = Date.today
    else
      commute_years = Date.new(years[0..3].to_i, years[4..-1].to_i, 1)
    end

    @nendo = get_nendo(commute_years)
    @gatudo = get_gatudo(commute_years)
    @project = get_project

    @commutes = current_user.commutes.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
    @reasons = current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s).first
    @date=@commutes.maximum(:updated_at ,:include)  #更新日時が一番新しいものを取得
    if @date==nil                                                 #更新日時が空なら今日の日付を使用
      @date=Date.today
    end
    @title = '現住所変更及び通勤届'
  end

  # GET /commutes/1/edit
  def edit
  end

  # POST /commutes
  # POST /commutes.json
  def create
    # @commute = Commute.new(commute_params)
    @commute = current_user.commutes.build(commute_params)

    respond_to do |format|
      if @commute.save
        format.html { redirect_to commutes_url, notice: 'データの登録を完了しました。' }
        format.json { render :show, status: :created, location: @commute }
      else
        format.html { render :new }
        format.json { render json: @commute.errors, status: :unprocessable_entity }
      end
    end
  end

  #
  # 本人確認処理
  #
  def check_proc
    init
    @commutes.update_all(["self_approved = ?",true])
    @reasons.update_all(["self_approved = ?",true])

    init true
    create_commutes true
    # create_reasons      二つあると二月分、月度が増える
  end

  #
  # 本人確認取消
  #
  def cancel_check_proc
    init
    @commutes.update_all(["self_approved = ?",false])
  end

  #
  # 上長承認処理
  #
  def approve_proc
    init
    @commutes.update_all(["boss_approved = ?",true])
  end

  #
  # 上長承認取消
  #
  def cancel_approval_proc
    init
    @commutes.update_all(["boss_approved = ?",false])
  end

  # PATCH/PUT /commutes/1
  # PATCH/PUT /commutes/1.json
  def update
    respond_to do |format|
      if @commute.update(commute_params)
        format.html { redirect_to commutes_url, notice: '編集を完了しました。' }
        format.json { render :show, status: :ok, location: @commute }
      else
        format.html { render :edit }
        format.json { render json: @commute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commutes/1
  # DELETE /commutes/1.json
  def destroy
    @commute.destroy
    respond_to do |format|
      format.html { redirect_to commutes_url, notice: 'データを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commute
      @commute = Commute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commute_params
      params.require(:commute).permit(:user_id, :year, :month, :reason, :reason_text, :transport, :segment1, :segment2, :money)
    end
    # =================================================================================================-
    #
  # 勤怠日付の初期化
  #
  def init(freezed=false)

    if changed_commute_years?
      session[:years] = params[:paper][:years]
    end

    @commute_years = get_years(current_user.commutes, freezed)

    @nendo = get_nendo(@commute_years)
    @gatudo = get_gatudo(@commute_years)
    @project = get_project

    @commutes = current_user.commutes.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)


     if changed_commute_years?
      session[:years] = params[:paper][:years]
    end

    @reason_years = get_years(current_user.reasons, freezed)

    @nendo = get_nendo(@reason_years)
    @gatudo = get_gatudo(@reason_years)
    @project = get_project

    @reasons = current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)

    @kintai_header = view_context.target_user.kintai_headers.find_by(year: @nendo.to_s,month: @gatudo.to_s)
  end



  def create_commutes(freezed=false)

    if @commutes.exists?
      @freezed = @commutes.first.freezed
      create_years_collection current_user.commutes, freezed
      return
    end

    if !@commutes.exists?
      target_date = Date.new(@commute_years.year, get_month(@commute_years), 16)


      @commute = current_user.commutes.build
      @commute[:year] = @nendo
      @commute[:month] = @gatudo
      if @commute.save
        @commutes << @commute
        target_date = target_date.tomorrow
      end
      @commutes = current_user.commutes.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
      @reasons = current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
    end
    create_years_collection current_user.commutes, freezed



  end

   def create_reasons(freezed=false)

    if @reasons.exists?
      @freezed = @reasons.first.freezed
      create_years_collection current_user.reasons, freezed
      return
    end

    if !@reasons.exists?
      target_date = Date.new(@commute_years.year, get_month(@commute_years), 16)


      @reason = current_user.reasons.build
      @reason[:year] = @nendo
      @reason[:month] = @gatudo
      if @reason.save
        @reasons << @reason
        target_date = target_date.tomorrow
      end
      # @commutes = current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
      @reasons = current_user.reasons.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
    end
    create_years_collection current_user.reasons, freezed
   end

  #   def init(freezed=false)

  #   unless session[:years].blank?
  #     @selected_nen_gatudo = session[:years]
  #   end

  #   if changed_transportation_express_years?
  #     @selected_nen_gatudo = params[:transportation_express][:nen_gatudo]
  #     session[:years] = params[:transportation_express][:nen_gatudo]
  #   end

  #   @transportation_express_years = get_transportation_express_years(params[:transportation_express], freezed)

  #   @nendo = get_nendo(@transportation_express_years)
  #   @gatudo = get_gatudo(@transportation_express_years)
  #   @project = get_project

  #   @transportation_express = current_user.transportation_expresses.where("year = ? and month = ?", @nendo.to_s, @gatudo.to_s)
  # end


  #
  # 対象年月のセレクトボックス内に含めるデータを作成する
  # @param [Boolean] freezed 呼び出し元が締め処理の場合にtrueを設定する。選択する対象年月を翌月に変更する。
  #
  def create_commute_years(freezed=false)
    @nen_gatudo = current_user.commutes.select("year ||  month as id, year || '年' || month || '月度' as value").group('year, month').order("id DESC")

    if freezed
      temp = session[:years]

      years = Date.new(temp[0..3].to_i, temp[4..-1].to_i, 1)
      next_years = years.months_since(1)

      @selected_nen_gatudo = "#{next_years.year}#{next_years.month}"
      session[:years] = @selected_nen_gatudo
    end
  end

  # 対象日付の月度を返す
  # @param [Date] target_date 対象日付
  # @return [Integer] 対象日付の月度
  def get_gatudo(target_date)
    gatudo = target_date.month

    if target_date.day > 15
      gatudo = target_date.months_since(1).month
    end

    gatudo
  end

  # 対象日付の年度を返す
  # @param [Date] target_date 対象日付
  # @return [Integer] 対象日付の年度
  def get_nendo(target_date)
    nendo = target_date.year

    if target_date.month == 12 and target_date.day > 15
      nendo = target_date.years_since(1).year
    end

    nendo
  end

  # 対象日付の月を返す
  # 対象日付の日が15日以前の場合に先月の月を返す。そうでない場合は当月の月を返す
  # @param [Date] target_date 対象日付
  # @return [Integer] 対象日付の月
  def get_month(target_date)
    month = target_date.month

    if target_date.day < 16
      month = target_date.months_ago(1).month
    end

    month
  end



  # 画面の対象年月が変更されたどうかを判定する
  # @return [Boolean] 対象年月が変更されている場合はtrueを返す。そうでない場合はfalseを返す
  def changed_commute_years?
    return ! params[:paper].nil?
  end

  # 画面に出力する勤怠日付を確定する
  # 締め処理の場合
  #   対象年月の翌月を返す
  # それ以外の場合
  #   対象年月を返す
  # @param [Date] tranportation_express
  # @param [Boolean] freezed 呼び出し元が締め処理の場合にtrueを設定する。選択する対象年月を翌月に変更する。
  # @return [Date] 対象勤怠日付
  def get_commute_years(transportation_express, freezed=false)

    unless session[:years].blank?
      temp = session[:years]
      years = Date.new(temp[0..3].to_i, temp[4..-1].to_i, 1)
    else

app/helpers/commutes_helper.rb
module CommutesHelper
end

app/views/commutes/_form.html.slim
= form_for @commute do |f|
  - if @commute.errors.any?
    #error_explanation
      h2 = "#{pluralize(@commute.errors.count, "error")} prohibited this commute from being saved:"
      ul
        - @commute.errors.full_messages.each do |message|
          li = message
  = f.hidden_field :year,value:@nendo if @commute.year.nil?
  = f.hidden_field :month,value:@gatudo if @commute.month.nil?

  .row
    .large-2.small-4.columns
      label.left.inline 交通機関名称
    .large-5.large-pull-5.small-8.columns
      = f.text_field :transport
  .row
    .large-2.small-4.columns
      label.left.inline 利用区間(出発)
    .large-5.large-pull-5.small-8.columns
      = f.text_field :segment1
  .row
    .large-2.small-4.columns
      label.left.inline 利用区間(到着)
    .large-5.large-pull-5.small-8.columns
      = f.text_field :segment2
  .row
    .large-2.small-4.columns
      label.left.inline １ヶ月の定期金額
    .large-5.large-pull-5.small-8.columns
      = f.number_field :money
  .row
    .large-3.large-centered.columns
      = f.submit '登録', class: "button radius"
      = link_to "戻る", commutes_path,class: "button radius gray"

app/views/commutes/edit.html.slim
article.commute_edit
	.row
		.large-12.columns
			h4 通勤届　修正 

	== render 'form'

app/views/commutes/index.html.slim
- @commutes.each do |commute|
  - @sum = commute.money.to_i + @sum.to_i
/ = hidden_field :sum, @sum
- session[:sum] = @sum
article.commute_index
  .row
    .large-12.columns

      h3
        i.fi-clipboard-pencil
        |現住所変更及び通勤届

      = render partial: 'shared/paper_proc', locals: { target: "commutes", users: @users, years: @years, kintai_header: @kintai_header, project: @project, status: @status, pre_path: create_pre_month_commutes_path, next_path: create_next_month_commutes_path }

      table style="border:none;"
        tr align="left" valign="top"
          td style="border:none;" width="290"

            table.sub style="border:none;padding-right:10px;" width="260"
              tr
                td width="70" 現住所
                td colspan="2" width="200" #{current_user.postal_code}#{current_user.prefecture}#{current_user.city}#{current_user.house_number}#{current_user.building}
                td
              tr
                td 電話番号
                td colspan="2" #{current_user.phone}
                td
              tr
                td.in 届出理由
                - if !@reasons.nil?
                  - if @reasons.reason == "new" && !@reasons.nil?
                    td.in colspan="2" 新規
                  - elsif @reasons.reason == "now" && !@reasons.nil?
                    td.in colspan="2" 現住所変更
                  - elsif @reasons.reason == "proj" && !@reasons.nil?
                    td.in colspan="2" プロジェクト変更
                  - elsif @reasons.reason == "tran" && !@reasons.nil?
                    td.in colspan="2" 通勤経路変更
                  - elsif @reasons.reason == "sai" && !@reasons.nil?
                    td.in colspan="2" 再提出
                  - elsif @reasons.reason == "up" && !@reasons.nil?
                    td.in colspan="2" 運賃値上げ
                  - elsif @reasons.reason == "ta" && !@reasons.nil?
                    td.in colspan="2" その他
                  - else
                    td.in colspan="2"
                -else
                  td.in colspan="2"　

                - if ! @reasons.nil?
                  td.in.text-center rowspan="2" width="35" = link_to edit_reason_path(@reasons),class:"button tiny radius" do
                    i.fi-plus
                - elsif @reasons.nil?
                  td rowspan="2" = link_to "新規", new_reason_path(@reasons) ,class: "button tiny success"

              tr
                td.in 届出理由<br>（その他）
                td.in colspan="2" = @reasons.reason_text if ! @reasons.nil?
          td style="border:none;"
            div
              table.main width="650"
                thead
                  tr
                    th width="90"交通機関名称
                    th width="200"利用区間１(出発)
                    th width="200"利用区間２(到着)
                    th width="110"１ヶ月の定期金額
                    th width="30"
                    th width="30"

                tbody
                  - @commutes.each do |commute|
                    tr
                      td = commute.transport
                      td = commute.segment1
                      td = commute.segment2
                      td#money = commute.money.to_s+'円'
                      td = link_to edit_commute_path(commute) , class:"button tiny radius" do
                        i.fi-plus
                      td = link_to commute, data: {:confirm => '削除してもよろしいですか？'}, :method => :delete ,class: "button tiny alert" do
                        i.fi-x
                  tr
                    td#kei colspan="3" 計
                    td#money #{@sum.to_s+'円'}
                    td colspan="2"

              br

app/views/commutes/new.html.slim
article.commute_edit
	.row
		.large-12.columns
			h4 通勤届　新規項目

	== render 'form'

	/ = link_to 'Back', commutes_path

app/views/commutes/print.pdf.slim
.row
	.large-12.columns
    article.commute_print
      br
      br
      table.title
        tr
        tr
          td#ate colspan="2" 総務人事部　　　　殿
          td
          td
          td width="70"style="border:solid 2px;border-right:solid 1px;border-bottom:solid 1px;"人事
          td width="70"style="border:solid 2px;border-right:solid 1px;border-bottom:solid 1px;border-left:solid 1px;"所属長
          td colspan="2" width="70" style="border:solid 2px;border-left:solid 1px;border-bottom:solid 1px;"本人

        tr
          td colspan="4" height="30"
          td rowspan="2"style="border:solid 2px;border-right:solid 1px;border-top:solid 1px;"
          td rowspan="2"style="border:solid 2px;border-right:solid 1px;border-top:solid 1px;border-left:solid 1px;"
          td rowspan="2" colspan="2" style="border:solid 2px;border-left:solid 1px;border-top:solid 1px;" = image_tag "#{current_user.imprint_id}.png", size: '40x40', class:"imprint"

        tr
          td width="70"
          td#title colspan="2" 現住所変更及び通勤届
          td width="50px"

        tr
          td
          td
          td
          td
          td#day colspan="3" width="140"  提出日 平成#{@nendo-1988}#{ @date.strftime("年%_m月%_d日")}


      table.user
        tr
          td rowspan="2" width="100"所　　　属
          td rowspan="2" width="200"#{current_user.section.name}
          td#ten width="90"社員コード
          td#ten width="110"#{current_user.employee_no}

        tr
          td 氏名
          td #{current_user.family_name}#{current_user.first_name}

        tr
          td rowspan="2"現　住　所
          td#zyusyo colspan="3" #{current_user.postal_code}#{current_user.prefecture}#{current_user.city}#{current_user.house_number}#{current_user.building}

        tr
          td style="border:none;"
          td#phone colspan="2"TEL #{current_user.phone}
        tr
          td 届　出　理　由
          td#reason colspan="3"
            - if @reasons.reason=='new'
              span#ok 新規
            - elsif @reasons.reason!='new'
              span 新規
            span ・
            - if @reasons.reason=='now'
              span#ok 現住所変更
            - elsif @reasons.reason!='now'
              span 現住所変更
            span ・
            - if @reasons.reason=='proj'
              span#ok プロジェクト変更
            - elsif @reasons.reason!='proj'
              span プロジェクト変更
            span ・
            - if @reasons.reason=='tran'
              span#ok 通勤経路変更
            - elsif @reasons.reason!='tran'
              span 通勤経路変更
            span ・
            - if @reasons.reason=='sai'
              span#ok 再提出
            - elsif @reasons.reason!='sai'
              span 再提出
            |<br>
            - if @reasons.reason=='up'
              span#ok 運賃値上げ
            - elsif @reasons.reason!='up'
              span 運賃値上げ
            span ・
            - if @reasons.reason=='ta'
              span#ok その他
            - elsif @reasons.reason!='ta'
              span その他
            | (
            - if @reasons.reason_text == nil
              span = "".ljust(20,"　")
            - else
              span = @reasons.reason_text.ljust(20,"　")
            / | (#{@reasons.reason_text})
            / その他の欄確保
            | )
      table.koutu
        tr#coltitle
          td width="100"交通機関名称
          td colspan="3" width="300" style="letter-spacing: 3em; "利用区間
          td width="100"１ヶ月の定期金額
          - @commutes.each do |commute|
            tr
              td width="100" = truncate("#{commute.transport}",:length=>26,:omission=>"…")
              td#kukan = truncate("#{commute.segment1}",:length=>26,:omission=>"…")
              td#yazirusi　・・・・⇒
              td#kukan = truncate("#{commute.segment2}",:length=>26,:omission=>"…")
              td#money = truncate("#{commute.money.to_s+'円'}",:length=>14,:omission=>"…")

          tr
            td
            td#money colspan="3"計　　
            td#money = truncate("#{@sum.to_s+'円'}",:length=>10,:omission=>"…")

          tr.nonborder
            td.nonborder colspan="5"　
          tr.nonborder
            td.nonborder colspan="5"株式会社　システム・スクゥェアー

app/views/commutes/show.html.slim
p#notice = notice

p
  strong User:
  = @commute.user_id
p
  strong Year:
  = @commute.year
p
  strong Month:
  = @commute.month
/ p
/   strong Reason:
/   = @commute.reason
/ p
/   strong Reason text:
/   = @commute.reason_text
p
  strong Transport:
  = @commute.transport
p
  strong Segment1:
  = @commute.segment1
p
  strong Segment2:
  = @commute.segment2
p
  strong Money:
  = @commute.money

= link_to 'Edit', edit_commute_path(@commute)
'|
= link_to 'Back', commutes_path